/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as projects from '../projects.js';

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference
} from 'convex/server';

declare const fullApi: ApiFromModules<{
  projects: typeof projects;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  /* biome-ignore lint: auto generated by convex service */
  FunctionReference<any, 'public'>
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  /* biome-ignore lint: auto generated by convex service */
  FunctionReference<any, 'internal'>
>;

/* biome-ignore lint: auto generated by convex service */
export declare const components: {};
